---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: rag5-aug13-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag5-aug13-1 
  name: rag5-aug13-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi